--- #YAML:1.0
module_name: Math-Prime-Simple
dist_version_from: lib/Math/Prime/Simple.pm
installdirs: site
requires:
    Exporter: 0
distribution_type: module
license: perl
dist_abstract: calculate prime numbers.
dist_author: Steven Schubiger
